# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/igneous',
                'doc_host': 'https://kelvinltse.github.io',
                'git_url': 'https://github.com/kelvinltse/igneous',
                'lib_path': 'igneous'},
  'syms': { 'igneous.core': {'igneous.core.foo': ('igneous.html#foo', 'igneous/core.py')},
            'igneous.igneous': { 'igneous.igneous.classify_image': ('igneous.html#classify_image', 'igneous/igneous.py'),
                                 'igneous.igneous.get_model_path': ('igneous.html#get_model_path', 'igneous/igneous.py')}}}
