# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/igneous',
                'doc_host': 'https://kelvinltse.github.io',
                'git_url': 'https://github.com/kelvinltse/igneous',
                'lib_path': 'igneous'},
  'syms': {'igneous.core': {'igneous.core.foo': ('core.html#foo', 'igneous/core.py')}}}
