"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/igneous.ipynb.

# %% auto 0
__all__ = ['learn', 'categories', 'get_model_path', 'classify_image']

# %% ../nbs/igneous.ipynb 2
from fastai.vision.all import *

# %% ../nbs/igneous.ipynb 4
from pathlib import Path

# Get the path relative to the module location
def get_model_path():
    try:
        # When running as a module
        module_path = Path(__file__).parent.parent / 'nbs' / 'export.pkl'
        if module_path.exists():
            return module_path
    except NameError:
        # When running in notebook
        notebook_path = Path('export.pkl')
        if notebook_path.exists():
            return notebook_path
        
       # Try relative to project root
        proj_path = Path('.') / 'nbs' / 'export.pkl'
        if proj_path.exists():
            return proj_path
            
    raise FileNotFoundError(f"Could not find export.pkl in expected locations")

learn = load_learner(get_model_path())

# %% ../nbs/igneous.ipynb 6
categories = ('granite', 'gabbro')

def classify_image(img):
    pred,idx,probs = learn.predict(img)
    return dict(zip(categories, map(float,probs)))
